# Santander Coders exercises from Class #2 Unit #2

Date: 02/07/2024. From: Ada Tech. Language: Portuguese.

In [1]:
import numpy as np

### Exercícios

Utilize comprehension para gerar a lista de todos os números interios entre 0 e 19. Converta a lista em um <font color='blue'>numpy</font> array bidimensional (matriz) com 4 linhas e 5 colunas.

In [2]:
arr1 = np.random.randint(0, 20, 30)
A = arr1.reshape((5, 6))

print("ARRAY\n", arr1, "\n")
print("MATRIZ\n", A)

ARRAY
 [ 8  7 17  8  7 12  7 14  9 10  5 15 14 17 12 16  7  8  6  1  5  7 18  4
  4  9 18  5 12 16] 

MATRIZ
 [[ 8  7 17  8  7 12]
 [ 7 14  9 10  5 15]
 [14 17 12 16  7  8]
 [ 6  1  5  7 18  4]
 [ 4  9 18  5 12 16]]


Construa um array unidimensional com 30 números inteiros escolhidos de forma randômica no intervalo entre 0 e 20. Reformate o array para que se torne uma matriz `A` com 5 linhas e 6 colunas.

In [3]:
# print(np.concatenate((a_5x6[0], a_5x6[1], a_5x6[3])).reshape((3, 6)), "\n")
print("LINHAS 0, 1, 3\n", A[[0, 1, 3], ::2], "\n")
print("LINHAS 1 E 2, COLUNAS 0, 2, 4\n", A[1:3, ::2], "\n")
print("LINHAS 1, 3, COLUNAS 1, 3\n", A[1:4:2, 1:4:2])

LINHAS 0, 1, 3
 [[ 8 17  7]
 [ 7  9  5]
 [ 6  5 18]] 

LINHAS 1 E 2, COLUNAS 0, 2, 4
 [[ 7  9  5]
 [14 12  7]] 

LINHAS 1, 3, COLUNAS 1, 3
 [[14 10]
 [ 1  7]]


Crie uma __view__ da matriz `A` gerada na célula anterior contendo:
- as linhas de `A` com índices 0,1 e 3
- as linhas de `A` com índice 1 e 2 e as colunas com índice 0,2 e 4
- as linhas de `A` com índice 1 e 3 e as colunas com índice 1 e 3

In [4]:
# print(np.concatenate((a_5x6[0], a_5x6[1], a_5x6[3])).reshape((3, 6)), "\n")
print("LINHAS 0, 1, 3\n", A[[0, 1, 3], ::2], "\n")
print("LINHAS 1 E 2, COLUNAS 0, 2, 4\n", A[1:3, ::2], "\n")
print("LINHAS 1, 3, COLUNAS 1, 3\n", A[1:4:2, 1:4:2])

LINHAS 0, 1, 3
 [[ 8 17  7]
 [ 7  9  5]
 [ 6  5 18]] 

LINHAS 1 E 2, COLUNAS 0, 2, 4
 [[ 7  9  5]
 [14 12  7]] 

LINHAS 1, 3, COLUNAS 1, 3
 [[14 10]
 [ 1  7]]


Construa um array `A` bidimensional 5x6 com 30 números inteiros escolhidos de forma randômica no intervalo entre 0 e 20. 
- faça uma cópia do array `A` criado, chamando a cópia de `Ac`
- Substitua todos os elementos do array `A` que sejam maiores que 10 pelo valor -1 
- Substitua todos os elementos do array `Ac` que sejam maiores que 7 e menores que 15 pelo valor -1 

__Dica:__ Gere máscaras booleanas para realizar as modificações nos arrays.

In [5]:
np.random.seed(1)
A = np.random.randint(0, 20, 30).reshape((5, 6))
print("ORIGINAL\n", A, "\n")

ac = A.copy()
maiores_dez = A > 10
maiores_sete = ac > 7
menores_quinze = ac < 15

A[maiores_dez] = -1
ac[maiores_sete & menores_quinze] = -1

print("ORIGINAL ALTERADA\n", A, "\n")
print("CÓPIA ALTERADA\n", ac)

ORIGINAL
 [[ 5 11 12  8  9 11]
 [ 5 15  0 16  1 12]
 [ 7 13  6 18  5 18]
 [11 10 14 18  4  9]
 [17  0 13  9  9  7]] 

ORIGINAL ALTERADA
 [[ 5 -1 -1  8  9 -1]
 [ 5 -1  0 -1  1 -1]
 [ 7 -1  6 -1  5 -1]
 [-1 10 -1 -1  4  9]
 [-1  0 -1  9  9  7]] 

CÓPIA ALTERADA
 [[ 5 -1 -1 -1 -1 -1]
 [ 5 15  0 16  1 -1]
 [ 7 -1  6 18  5 18]
 [-1 -1 -1 18  4 -1]
 [17  0 -1 -1 -1  7]]


Construa um array `A` com 20 linhas e 10 colunas onde os elementos são os números interios de  1 até 200.
- Crie uma __view__ de `A` chamada `A_lpares` contendo apenas as linhas de `A` com índice par. 
- Crie uma __view__ de `A` chamada `A_lpares_cimpares` contendo as linhas `A` com índice par e colunas com índice ímpar. 

In [6]:
np.random.seed(1)
A = np.random.randint(1, 200, 20 * 10).reshape((20, 10))
print("ORIGINAL\n", A, "\n")

a_lpares = A[::2]
a_lpares_cimpares = A[::2, 1::2]

print("LINHAS PARES\n", a_lpares, "\n")
print("LINHAS PARES, COLUNAS ÍMPARES\n", a_lpares_cimpares)

ORIGINAL
 [[ 38 141  73 138 134  80 193 145 130  72]
 [135  26 179  21 102 147 140 157 158 143]
 [ 51  69  97  87 142 138   8  64  62  23]
 [ 58   2 129  61   9 142 116 176 122  31]
 [ 72 132 199 150  50  58   4 197  25  44]
 [ 77  27  53  81 110 116  42  16  65 197]
 [ 26 112 136  27 154 105  23  10 196 127]
 [ 24 126 101 156 166  58  84 167 137  33]
 [163  11  24 144  88  26  93  75 191  47]
 [161 152 184  66 114  78   4 129   7  53]
 [199   3  77 150   8  78  76  77  44  21]
 [ 31  37 104   8  46 197  58  97  14  11]
 [ 24 125  82 136 122 153 149 161 141 194]
 [ 95  61 153  83 116  98 131 104  99  11]
 [183  97  83 199 195  72 177  55  16 134]
 [146 171  21 119 177  23 142 115  98 182]
 [ 85  11  97 184  62  57 150  97  26 143]
 [142 117  44 135 185 188 144  25 138 195]
 [ 54  70 165 102  22  41  78 178 114  48]
 [169  46  88 145 157  46 196 117  67  47]] 

LINHAS PARES
 [[ 38 141  73 138 134  80 193 145 130  72]
 [ 51  69  97  87 142 138   8  64  62  23]
 [ 72 132 199 150  50  58  

Substitua os elememtos do array `A` do exercício anterior por -1 quando pelo menos um dos índices do elemento é par. 

__Dica:__ Construa uma máscara booleana

In [7]:
A[::2] = A[::, ::2] = -1
print("ÍNDICES PARES SUBSTITUÍDOS POR -1\n", A)

ÍNDICES PARES SUBSTITUÍDOS POR -1
 [[ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1  26  -1  21  -1 147  -1 157  -1 143]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1   2  -1  61  -1 142  -1 176  -1  31]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1  27  -1  81  -1 116  -1  16  -1 197]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1 126  -1 156  -1  58  -1 167  -1  33]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1 152  -1  66  -1  78  -1 129  -1  53]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1  37  -1   8  -1 197  -1  97  -1  11]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1  61  -1  83  -1  98  -1 104  -1  11]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1 171  -1 119  -1  23  -1 115  -1 182]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1 117  -1 135  -1 188  -1  25  -1 195]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1  46  -1 145  -1  46  -1 117  -1  47]]


Construa uma função chamada `ordena_linhas` que recebe uma matriz como parâmetro e troque as linhas de posição para que fiquem ordenadas de acordo com a primeira coluna. Por exemplo:
```python
A = np.array([[20, 26, 12], 
              [8, 3, 26], 
              [3, 10, 4]])
print(ordena_linhas(A))
```
deve resultar em
```python
[[ 3 10  4]
 [ 8  3 26]
 [20 26 12]]
```

In [8]:
def ordena_linhas(mtx):
    sort_coluna1 = mtx[:,0].argsort()
    return mtx[sort_coluna1]

A = np.array([[20, 26, 12], 
              [8, 3, 26], 
              [3, 10, 4]])

print(ordena_linhas(A))

[[ 3 10  4]
 [ 8  3 26]
 [20 26 12]]
